import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LocalFont from "next/font/local";
import "./globals.css";
import { PageProvider } from "@/context/PageContext";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const agbalumo = LocalFont({
  src: "../assets/fonts/Agbalumo-Regular.ttf",
  variable: "--font-agbalumo",
});

export const metadata: Metadata = {
  title: "GSAP Animations",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <PageProvider>
        <body className={`${inter.variable} ${agbalumo.variable} font-inter`}>
          <Navbar />
          <div className="pt-[50px]">{children}</div>
        </body>
      </PageProvider>
    </html>
  );
}
